### ISSUE TITLE
Is it possible to include the pipe.py file?

### ISSUE THREAD

**Issue by alpecorale** [FDA/Cancer-CoCoPUTs#1]
Trying to make our own tables, but pipe.py is not included.

**Comment by roxanne-gh** [comment]
> Trying to make our own tables, but pipe.py is not included.


Hi 
you can find pipe.py in the "GRCh38_junction_dinucleotides_w_ENSG.zip" zip folder. If you extract all files from all zip folders you should end up with everything you'll need for this tool.
